### ISSUE TITLE
Slider speed

### ISSUE THREAD

**Issue by KayzerCode** [ronaldaug/styler#3]
Hi! How to control the speed of slides changing?

**Comment by ronaldaug** [comment]
I use [tiny slider](https://github.com/ganlanyuan/tiny-slider), you can also check their documentation [here](https://github.com/ganlanyuan/tiny-slider#options). 

You can add speed option in slider configuration which is inside `js/main.js`

```javascript

  /* -------------------------------------
    Tiny slider config
    ---------------------------------------- */
    var slider = tns({
        container: '#slider',
        items: 1,
        slideBy: 'page',
        speed:100,
        autoplayButtonOutput:false,
        controls:false,
        autoplay: true,
        mouseDrag:true
      });

```

In this above code, I added `speed:100`, and 100 is in milliseconds. 

Hope it help you.
